---
title: "BTM test"
output: html_notebook
---

Using [BTM cran package](https://cran.r-project.org/web/packages/BTM/BTM.pdf), based on [this](https://github.com/bnosac/BTM) GitHub code.

```{r}
library(udpipe)
library(BTM) # topic modelling

# visualise model
library(textplot)
library(ggraph)
library(concaveman)
```

```{r}
data("brussels_reviews_anno", package = "udpipe")
```

```{r}
## Taking only nouns of Dutch data
x <- subset(brussels_reviews_anno, language == "nl")
x <- subset(x, xpos %in% c("NN", "NNP", "NNS"))
x <- x[, c("doc_id", "lemma")]

## Building the model
set.seed(321)
model  <- BTM(x, k = 3, beta = 0.01, iter = 1000, trace = 100)
```

```{r}
## Inspect the model - topic frequency + conditional term probabilities
model$theta
```
```{r}
topicterms <- terms(model, top_n = 10)
topicterms
```

```{r}
scores <- predict(model, newdata = x)
```

```{r}
# If you set background to TRUE
# The first topic is set to a background topic that equals to the empirical word distribution. 
# This can be used to filter out common words.
set.seed(1234)
model      <- BTM(x, k = 5, beta = 0.01, background = TRUE, iter = 1000, trace = 100)
topicterms <- terms(model, top_n = 5)
topicterms
```

```{r}
plot(model)
```





